osate/osate2-core#1141
osate/osate2-plugins pull request #101
Opened 2018-04-19 14:17 UTC by reteprelief

Fixes osate/osate2-core#1141

2018-04-20 19:14 UTC, joeseibel submitted a review, later dismissed

2018-04-20 19:17 UTC, joeseibel requested changes
Branch has conflicts and cannot be merged.

2018-04-22 15:54 UTC, reteprelief commented
Resolved the conflict.

2018-04-23 19:15 UTC, joeseibel approved these changes

2018-04-23 19:15 UTC, merged